name: My first Workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest

        steps: 

        - name: Checkout
          uses: actions/checkout@v6

        - name: Welcome Message
          run: echo "Welcome to GitHub Actions"

        - name: List Files
          run: ls

        - name: Cat Files
          run: |
           echo "Namaskaaaram unde......." > file
           cat file