name: Webserver Version

on: 
  push:
  workflow_dispatch:

jobs:
  "Webserver-Version":
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          SOURCE: "./"
          TARGET: "/tmp/deploy"
          # Optional: Add any extra rsync arguments here
          ARGS: "-avzh --delete"
          # This runs the final command on your server after the transfer
          SCRIPT_AFTER: |
            sudo rsync -avzh --delete /tmp/deploy/ /var/www/html/
            sudo rm -rf /tmp/deploy/*