name: My first Workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest

        steps: 

        - name: Checkout
          uses: actions/checkout@v6

        - name: Welcome Message
          run: echo "Welcome to GitHub Actions"

        - name: Generating ASCII art
          run: |
            sudo apt install cowsay -y
            cowsay -f dragon "Grrrrr......" > dragon.txt
            cat dragon.txt

        