---
name: Input Testing
on:
  workflow_dispatch:
    inputs:
        Name:
        description: Your Name
        required: true
        default: Paalu
        type: choice
        options:
          - Makku
          - Chmitt
          - Ajin
      happy:
        description: 'Are you happy?'
        required: false
        type: boolean
jobs:
  test:
    runs-on: ubuntu-latest
    
