---
name: Input Testing
on:
  workflow_dispatch:
    inputs:
        name:
        description: Your Name
        required: true
        default: Paalu
        type: choice
        options:
          - Makku
          - Chmitt
          - Ajin
      happy:
        description: 'Are you happy?'
        required: false
        type: boolean
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Name
        run: |
          echo "My name is ${{ inputs.name }}"
          echo "Are you happy - ${{ inputs.happy }}"
    
