name: Generate ASCII art

on: 
  push:
  workflow_dispatch:
    inputs:
      message:
        description: "Message for cowsay"
        required: true
        default: "Hello"

jobs:
  build-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        run: echo "Message is: ${{ github.event.inputs.message }}"
