---
name: Matrix Configuration
on: 
  push:
  workflow_dispatch:

jobs:
  deployment-on-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, ubuntu-20.04]
        images: [hello-world, alpine]

    runs-on: ubuntu-latest
    steps:
      - name: Echo Docker Details
        run: docker info
     
      - name: Run Images
        run: docker run hello-world
  
